export enum StatusOrder {
    RECEIVED_ORDER = 1,
    TRANSACTION_IN_RED,
    TRANSACTION_CONFIRMATED_IN_RED,
    ORDER_FOR_PAYMENT,
    CONFIRMATED_PAYMENT,
    ORDER_COMPLETED,
    ORDER_CANCELED,
}